export const CURSOR_ON_EDGE_MARGIN = 30 // px
export const ELEMENT_AUTO_MOVE_SPEED = 20 // ms
export const ELEMENT_AUTO_MOVE_STEP = 15 // px
export const ZOOM_DESKTOP_DEFAULT_STEP = 0.25 // transform scale
export const ZOOM_NON_DESKTOP_DEFAULT_STEP = 0.04 // transform scale
export const ZOOM_MIN_DEFAULT = 0.3
export const ZOOM_MAX_DEFAULT = 5
export const ZOOM_SPEED_DEFAULT = 1
export const ZOOM_PRECISION = 100.0;
export const ZOOM_ANIMATION_DELAY = 300 // ms
export const ZOOM_ANIMATION_DELAY_STR = `${ZOOM_ANIMATION_DELAY / 1000}s`
export const ZOOM_DESKTOP_THROTTLE_DELAY = 100 // ms
export const ZOOM_INITIAL = 1
export const ZOOM_NON_DESKTOP_THROTTLE_DELAY = 5 // ms
export const ZOOM_NON_DESKTOP_MOVING_BLOCK_DELAY = 300 // ms
